### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ioistired** [Narasimha1997/smartreply#1]
Hi there. I would like to run your code, but without a valid software license, I have no legal permission to do so. Please apply a license to your project.

A few licenses that I would recommend, depending on how you want people to use your code, are:

- [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/)
- [MPL 2.0](https://choosealicense.com/licenses/mpl-2.0/)
- [GNU AGPLv3](https://choosealicense.com/licenses/agpl-3.0/)

**Comment by Narasimha1997** [comment]
@iomintz 
Added `MIT` license, please feel free to make any changes and also you are welcome to make contributions to this repository.

See #2
